### ISSUE TITLE
[feat] 간호사 메인 화면 구현

### ISSUE THREAD

**Issue by kangyuri1114** [SSU-Capstone-Aurora/CareVision-Android#18]
### 💼 작업 설명

간호사 메인 로직 화면 구현

### ✅ To-do

- [ ] 메인 화면
- [ ] 알림화면
- [ ] 베드별 영상보기 화면
- [ ] 실시간 영상보기 화면
- [ ] 담당환자 목록 화면
