### ISSUE TITLE
[feat]: 간호사 회원가입, 온보딩 로직 구현

### ISSUE THREAD

**Issue by kangyuri1114** [SSU-Capstone-Aurora/CareVision-Android#27]
### 💼 작업 설명

간호사 회원가입, 온보딩 로직 구현

### ✅ To-do

- [ ] 회원가입 시 유효성 검사
- [ ] 검색 기능 구현
- [ ] 과 선택 메뉴 컴포넌트 구현
